# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20160620_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Withdrawal', 'Debit'), ('Deposit', 'Credit')], default='Withdrawal', max_length=10),
        ),
    ]
